# Generated by Django 4.1.5 on 2023-02-23 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TimeSeries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateField(verbose_name='Date')),
                ('Time', models.TimeField(verbose_name='Time')),
                ('Temp', models.FloatField(verbose_name='Temperature')),
                ('Humidity', models.FloatField(verbose_name='Humidity')),
                ('GPOA', models.FloatField(verbose_name='GPOA(W/M2)')),
                ('panel', models.CharField(max_length=100, verbose_name='EDS/CTRL(#)')),
                ('Voc_Before', models.FloatField(verbose_name='Voc_Before(V)')),
                ('Voc_After', models.FloatField(verbose_name='Voc_After(V)')),
                ('Isc_Before', models.FloatField(verbose_name='Isc_Before(A)')),
                ('Isc_After', models.FloatField(verbose_name='Isc_After(A)')),
                ('Pout_Before', models.FloatField(verbose_name='Pout_Before(W)')),
                ('Pout_After', models.FloatField(verbose_name='Pout_After(W)')),
                ('PR_Before', models.FloatField(verbose_name='PR_Before')),
                ('PR_After', models.FloatField(verbose_name='PR_After')),
                ('SI_Before', models.FloatField(verbose_name='SI_Before')),
                ('SI_After', models.FloatField(verbose_name='SI_After')),
            ],
        ),
    ]
