# Generated by Django 4.1.5 on 2023-02-23 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pv_dashboard', '0002_alter_timeseries_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeseries',
            name='Date',
            field=models.CharField(max_length=100, verbose_name='Date'),
        ),
    ]
